replicaCount: 1

image:
  repository: bpu2/skil2-2-voorbeeldproject3
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080   # Choose a port in the 30000-32767 range

env:
  APP_ENV: production
