apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skil2-2-voorbeeldproject3.db.fullname" . }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "skil2-2-voorbeeldproject3.db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "skil2-2-voorbeeldproject3.db.name" . }}
    spec:
      containers:
        - name: db
          image: "mysql:5.7"
          imagepullPolicy: {{ .Values.database.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.database.env.MYSQL_ROOT_PASSWORD }}
            - name: MYSQL_DATABASE
              value: {{ .Values.database.env.MYSQL_DATABASE }}
            - name: MYSQL_USER
              value: {{ .Values.database.env.MYSQL_USER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.database.env.MYSQL_PASSWORD }}
          ports:
            - containerPort: 3306
