apiVersion: v1
kind: Service
metadata:
  name: {{ include "skil2-2-voorbeeldproject3.db.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ include "skil2-2-voorbeeldproject3.db.name" . }}
